site_name: Motoko-lib
repo_name: research-ag/motoko-lib
repo_url: https://github.com/research-ag/motoko-lib
site_url: https://research-ag.github.io/motoko-lib/
copyright: Copyright &copy; 2023 MR Research AG
nav:
  - Home: home.md
  - Modules:
    - Vector: modules/vector.md
    - Sha2: modules/sha2.md
  - Mo-docs:
    - Vector: modoc/Vector.md
    - Sha256: modoc/Sha256.md
    - Sha512: modoc/Sha512.md
  - Contribute: contribute.md
  - About: about.md
theme:
  name: material
  language: en
  icon:
    logo: material/library
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      title: On this page
      permalink: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js